var a = "variable";
var b = 5;
var c = true;
var d = ['a', 'b', 'c'];
var e;
console.log("a = " + a);
console.log("b = " + b);
console.log("c = " + c);
console.log("d = " + d);
console.log("e = " + e);
